backend:
  name: git-gateway
  branch: master
media_folder: "src/static/img"
public_folder: "/static/img"

collections:
  - label: "Blog"
    name: "blog"
    folder: "src/posts"
    create: true
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
      - widget: select
        label: "Tags"
        name: "tags"
        multiple: true
        create: true
        options: ["Tags", "created", "from"]
      - { label: "Is Published", name: "isPublished", widget: "boolean", default: false }
      - { label: "Is Restricted", name: "isRestricted", widget: "boolean", default: false }

  - label: "Settings"
    name: "settings"
    editor:
      preview: false
    files:
      - label: "Blog Page Settings"
        name: "blogPageSettings"
        file: "src/_data/blogPageSettings.yaml"
        fields:
          - { label: "Show Blog Header", name: "show_section", widget: "boolean" }

          - { label: "Header", name: "header", widget: "string" }
          - { label: "Subheader", name: "subheader", widget: "string" }
          - { label: "SEO Content", name: "seoContent", widget: "text" }
          - { label: "Image", name: "image", widget: "image" }    
      - label: "Navigation"
        name: "items"
        file: "src/_data/navigation.yaml"
        fields:
          - label: "Nav Items"
            name: "items"
            widget: "list"
            allow_add: false
            collapsed: false
            fields:
              - { label: "Show", name: "show_nav_item", widget: "boolean", default: false, hint: "Enable to show this link on the navigation bar" }
              - { label: "Title", name: "text", widget: "string" }
              - { label: "URL", name: "url", widget: "string" }

      - label: "Quick Links"
        name: "links"
        file: "src/_data/quicklinks.yaml"
        fields:
          - { label: "Show Section", name: "show_section", widget: "boolean" }
          - { label: "Header", name: "header", widget: "string" }
          - { label: "Short Description", name: "shortDescription", widget: "text" }
          - label: "Links"
            name: "links"
            widget: "list"
            collapsed: false
            allow_add: true
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "URL", name: "url", widget: "string" }
              - { label: "Description", name: "desc", widget: "string" }

      - label: "Meta Settings"
        name: "settings"
        file: "src/_data/settings.yaml"
        fields:
          - { label: "Show Footer", name: "show_footer", widget: "boolean" }

          - { label: "Name", name: "name", widget: "string" }
          - { label: "Author", name: "author", widget: "string" }
          - { label: "URL", name: "url", widget: "string" }
          - { label: "Site Title", name: "siteTitle", widget: "string" }
          - { label: "Site SEO description", name: "siteSeoDescription", widget: "string" }

      - label: "Store Settings"
        name: "snipcartSettings"
        file: "src/_data/snipcartSettings.yaml"
        fields:
          - { label: "Snipcart API Key", name: "name", widget: "string" }

      - label: "Home Page Settings"
        name: "homeSettings"
        file: "src/_data/homeSettings.yaml"
        fields:
          - label: "Direction"
            name: "direction"
            widget: "boolean"
            default: false
            hint: "Enable for RTL. Leave disabled for LTR."

      - label: "About"
        name: "about"
        file: "src/_data/about.yaml"
        fields:
          - { label: "Show Section", name: "show_section", widget: "boolean" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Content", name: "content", widget: "text" }
          - { label: "Image", name: "image", widget: "image" }

      - label: "Testimonials"
        name: "testimonials"
        file: "src/_data/testimonials.yaml"
        fields:
          - { label: "Show Section", name: "show_section", widget: "boolean" }
          - { label: "Header", name: "header", widget: "string" }
          - { label: "Short Description", name: "shortDescription", widget: "text" }
          - label: "Testimonial Items"
            name: "testimonials"
            widget: "list"
            fields:
              - { label: "Full Name", name: "name", widget: "string" }
              - { label: "Content", name: "content", widget: "text" }
              - { label: "Image", name: "image", widget: "image" }
              - { label: "Job", name: "job", widget: "string" }

      - label: "Features"
        name: "features"
        file: "src/_data/features.yaml"
        fields:
          - { label: "Show Section", name: "show_section", widget: "boolean" }
          - { label: "Header", name: "header", widget: "string" }
          - { label: "Short Description", name: "shortDescription", widget: "text" }
          - label: "Feature Items"
            name: "features"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Content", name: "content", widget: "text" }
              - { label: "Image", name: "image", widget: "image" }

      - label: "Inline Banners"
        name: "inlineBanners"
        file: "src/_data/inlineBanners.yaml"
        fields:
          - { label: "Show Section", name: "show_sction", widget: "boolean", default: true, hint: "Select to show or hide this section in Home page" }
          - { label: "Header", name: "header", widget: "string" }
          - { label: "Short Description", name: "shortDescription", widget: "text" }
          - label: "Inline Banner Items"
            name: "inlineBanners"
            widget: "list"
            fields:
              - { label: "Banner Title", name: "title", widget: "string" }
              - { label: "Banner Image", name: "image", widget: "image" }

      - label: "Hero"
        name: "hero"
        file: "src/_data/hero.yaml"
        fields:
          - { label: "Show Section", name: "show_section", widget: "boolean" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Subtitle", name: "subtitle", widget: "string" }
          - { label: "Image", name: "image", widget: "image" }
